import { useState, useEffect, useRef } from "react";
import { useParams, Link } from "wouter";
import { useGetAnalysis, getGetAnalysisQueryKey } from "@workspace/api-client-react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { TrustScore } from "@/components/trust-score";
import { PlatformIcon } from "@/components/platform-icon";
import { useToast } from "@/hooks/use-toast";
import {
  ArrowLeft, ExternalLink, AlertTriangle, ShieldAlert, ShieldCheck,
  Search, ScanLine, FileText, CheckCircle2, Activity, Copy, Check,
} from "lucide-react";

const platformAccent: Record<string, string> = {
  amazon:     "hover:border-[#FF9900]/50 hover:shadow-[#FF9900]/10",
  noon:       "hover:border-[#FEEE00]/40 hover:shadow-[#FEEE00]/10",
  ebay:       "hover:border-[#E53238]/40 hover:shadow-[#E53238]/10",
  alibaba:    "hover:border-[#FF6A00]/50 hover:shadow-[#FF6A00]/10",
  aliexpress: "hover:border-[#E43225]/50 hover:shadow-[#E43225]/10",
};

const basisLabel: Record<string, { label: string; color: string }> = {
  known_fact: { label: "Known Fact",       color: "text-blue-400 border-blue-400/30 bg-blue-400/8" },
  pattern:    { label: "Category Pattern", color: "text-purple-400 border-purple-400/30 bg-purple-400/8" },
  inference:  { label: "Inference",        color: "text-orange-400 border-orange-400/30 bg-orange-400/8" },
};

export default function Analysis() {
  const params = useParams();
  const id = params.id ? parseInt(params.id) : 0;
  const { toast } = useToast();

  // ── All hooks unconditionally at the top ──────────────────────────────────
  const prevStatus = useRef<string | null>(null);
  const [revealed, setRevealed] = useState(false);
  const [elapsed, setElapsed] = useState(0);
  const [copied, setCopied] = useState(false);

  const { data: analysis, isLoading, isError } = useGetAnalysis(id, {
    query: {
      enabled: !!id,
      queryKey: getGetAnalysisQueryKey(id),
      refetchInterval: (query) => {
        const data = query.state.data;
        if (data && (data.status === "pending" || data.status === "processing")) return 2000;
        return false;
      },
    },
  });

  // Toast when analysis completes while tab is hidden
  useEffect(() => {
    if (!analysis) return;
    if (prevStatus.current && prevStatus.current !== "completed" && analysis.status === "completed") {
      if (document.hidden) {
        toast({
          title: "Analysis complete",
          description: `Background check finished for: ${(analysis.result as any)?.productTitle ?? "your product"}`,
        });
      }
    }
    prevStatus.current = analysis.status;
  }, [analysis?.status]);

  // Staggered reveal once result arrives
  useEffect(() => {
    if (analysis?.status === "completed") {
      const t = setTimeout(() => setRevealed(true), 50);
      return () => clearTimeout(t);
    } else {
      setRevealed(false);
    }
  }, [analysis?.status]);

  // Elapsed timer for loading step progression
  useEffect(() => {
    if (analysis && (analysis.status === "pending" || analysis.status === "processing")) {
      setElapsed(0);
      const interval = setInterval(() => setElapsed((s) => s + 1), 1000);
      return () => clearInterval(interval);
    }
  }, [analysis?.status]);

  // Copy report handler
  function copyReport() {
    const result = analysis?.result as any;
    if (!result) return;
    const lines = [
      `LISTER THE DETECTIVE — Analysis Report`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `Product: ${result.productTitle}`,
      `Brand:   ${result.brand}`,
      analysis?.url ? `URL:     ${analysis.url}` : "",
      ``,
      `VERDICT: ${result.verdict?.toUpperCase()} (Trust Score: ${result.overallTrustScore}/100)`,
      `Price:   ${result.estimatedPrice ?? "Unknown"}`,
      ``,
      `SUMMARY`,
      result.summary,
      ``,
      result.disclaimer ? `NOTE: ${result.disclaimer}` : "",
      ``,
      `RED FLAGS`,
      ...(result.redFlags ?? []).map((f: any) => `  [${f.severity?.toUpperCase()}] ${f.description} (${f.basis ?? "inference"})`),
      ``,
      `SELLER ANALYSIS`,   result.sellerAnalysis,
      ``,
      `SPECS REALITY`,     result.specsAnalysis,
      ``,
      `REVIEW AUTHENTICITY`, result.reviewsAnalysis,
      ``,
      `BRAND TRUST`,       result.brandTrustAnalysis,
      ``,
      `SAME PRODUCT — BETTER SOURCES`,
      ...(result.alternatives ?? []).map((a: any, i: number) =>
        `  ${i + 1}. ${a.title} on ${a.platform} — ${a.price ?? "?"} (score: ${a.trustScore})\n     ${a.whyBetter}\n     ${a.url ?? ""}`
      ),
      ``,
      `Generated by Lister the Detective`,
    ].filter((l) => l !== undefined).join("\n");

    navigator.clipboard.writeText(lines).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }
  // ─────────────────────────────────────────────────────────────────────────

  // Loading splash
  if (isLoading || !analysis) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center p-8 bg-muted/20">
        <Activity className="w-12 h-12 text-primary animate-pulse mb-6" />
        <h2 className="text-xl font-bold font-mono tracking-tight">Initializing Scanner...</h2>
      </div>
    );
  }

  // Error / failed
  if (isError || analysis.status === "failed") {
    return (
      <div className="container max-w-3xl mx-auto py-16 px-4">
        <Button variant="ghost" asChild className="mb-8 font-mono text-xs uppercase tracking-wider">
          <Link href="/"><ArrowLeft className="w-4 h-4 mr-2" /> Back to Search</Link>
        </Button>
        <Card className="border-destructive/50 bg-destructive/5">
          <CardContent className="p-12 text-center flex flex-col items-center">
            <AlertTriangle className="w-16 h-16 text-destructive mb-6" />
            <h2 className="text-2xl font-bold mb-2">Analysis Failed</h2>
            <p className="text-muted-foreground font-mono mb-4 max-w-md mx-auto">
              {(analysis as any).errorMessage || "We couldn't complete the background check on this product."}
            </p>
            <p className="text-muted-foreground/60 font-mono text-xs mb-8 max-w-md mx-auto">
              Tip: If you used a short link (e.g. amzn.eu/...), paste the full URL from your browser's address bar instead.
            </p>
            <Button asChild className="font-mono text-sm tracking-widest uppercase">
              <Link href="/">Try Another Product</Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Loading steps
  if (analysis.status === "pending" || analysis.status === "processing") {
    const steps = [
      { icon: ScanLine,    text: "Identifying product & brand from URL..." },
      { icon: FileText,    text: "Analyzing brand reputation & seller norms..." },
      { icon: ShieldAlert, text: "Checking review authenticity patterns..." },
      { icon: Search,      text: "Finding the same product on other platforms..." },
    ];
    const activeStep = Math.min(Math.floor(elapsed / 8), steps.length - 1);

    return (
      <div className="flex-1 flex flex-col items-center justify-center p-8 bg-background relative overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-primary/5 via-background to-background" />
        <div className="relative z-10 w-full max-w-md">
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-24 h-24 rounded-full bg-primary/10 mb-6 relative">
              <div className="absolute inset-0 rounded-full border-4 border-primary/20 border-t-primary animate-spin" />
              <Search className="w-10 h-10 text-primary" />
            </div>
            <h2 className="text-3xl font-bold tracking-tighter mb-2">Detective at work</h2>
            <p className="text-muted-foreground font-mono text-sm">Running a full background check — hang tight.</p>
          </div>
          <div className="space-y-4 border border-border/50 rounded-xl p-6 bg-card/50 backdrop-blur-sm shadow-xl">
            {steps.map((step, index) => {
              const Icon = step.icon;
              const isDone = index < activeStep;
              const isActive = index === activeStep;
              return (
                <div key={index} className={`flex items-center gap-4 transition-all duration-700 ${isActive ? "opacity-100" : isDone ? "opacity-55" : "opacity-15"}`}>
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 transition-colors ${isDone ? "bg-green-500/20 text-green-400" : isActive ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>
                    {isDone ? <CheckCircle2 className="w-4 h-4" /> : <Icon className={`w-4 h-4 ${isActive ? "animate-pulse" : ""}`} />}
                  </div>
                  <span className="font-mono text-sm">{step.text}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    );
  }

  const result = analysis.result as any;
  if (!result) return null;

  // ── Result UI ─────────────────────────────────────────────────────────────
  return (
    <div className="container max-w-6xl mx-auto py-8 px-4">
      {/* Top bar */}
      <div className="flex items-center justify-between mb-6">
        <Button variant="ghost" asChild className="font-mono text-xs uppercase tracking-wider text-muted-foreground hover:text-foreground">
          <Link href="/"><ArrowLeft className="w-4 h-4 mr-2" /> New Search</Link>
        </Button>
        <Button variant="outline" size="sm" onClick={copyReport} className="font-mono text-xs uppercase tracking-wider gap-2">
          {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
          {copied ? "Copied!" : "Copy Report"}
        </Button>
      </div>

      {/* Header — stagger-reveal */}
      <div className={`flex flex-col lg:flex-row gap-6 items-start mb-10 transition-all duration-500 ${revealed ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"}`}>
        <div className="flex-1 space-y-3 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            {result.platform && (
              <Badge variant="outline" className="px-3 py-1 font-mono uppercase tracking-wider text-xs border-primary/30 text-primary">
                <PlatformIcon platform={result.platform} className="w-3 h-3 mr-1.5" />
                {result.platform}
              </Badge>
            )}
            <Badge variant="secondary" className="px-3 py-1 font-mono uppercase tracking-wider text-xs">{result.brand}</Badge>
          </div>

          <h1 className="text-2xl md:text-3xl lg:text-4xl font-bold tracking-tight leading-tight">{result.productTitle}</h1>

          {analysis.url && (
            <a href={analysis.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center text-xs font-mono text-primary hover:underline">
              View Original Listing <ExternalLink className="w-3 h-3 ml-1.5" />
            </a>
          )}

          <div className="p-4 bg-muted/30 rounded-lg border border-border/50 text-foreground/80 font-mono text-sm leading-relaxed">
            {result.summary}
          </div>

          {result.disclaimer && (
            <div className="flex items-start gap-2 px-3 py-2 rounded-lg bg-blue-500/8 border border-blue-500/20 text-blue-300/80 font-mono text-xs leading-relaxed">
              <ShieldCheck className="w-3.5 h-3.5 shrink-0 mt-0.5 text-blue-400" />
              <span>{result.disclaimer}</span>
            </div>
          )}
        </div>

        {/* Trust score card — horizontal on mobile, vertical on desktop */}
        <Card className="w-full lg:w-64 shrink-0 border-border/50 shadow-xl bg-card/80 backdrop-blur-sm relative overflow-hidden">
          <div className={`absolute top-0 left-0 w-full h-1 ${result.verdict === "recommended" ? "bg-green-500" : result.verdict === "caution" ? "bg-yellow-500" : "bg-red-500"}`} />
          <CardContent className="p-6 flex flex-row lg:flex-col items-center lg:text-center gap-6 lg:gap-0">
            <div className="flex flex-col items-center">
              <h3 className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground mb-3">Trust Index</h3>
              <TrustScore score={result.overallTrustScore} size="lg" showLabel />
            </div>
            <div className="flex-1 lg:w-full lg:pt-4 lg:border-t lg:border-border/50 lg:mt-4">
              <span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground block mb-1">Est. Price</span>
              <span className="text-xl font-bold">{result.estimatedPrice || "Unknown"}</span>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Red Flags */}
      {result.redFlags && result.redFlags.length > 0 && (
        <div className={`mb-10 transition-all duration-500 delay-100 ${revealed ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"}`}>
          <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
            <ShieldAlert className="w-5 h-5 text-destructive" />
            Detective Findings: Red Flags
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {result.redFlags.map((flag: any, idx: number) => {
              const sev = {
                high:   { wrapper: "bg-red-500/10 border-red-500/30",    icon: "text-red-400",           badge: "bg-red-500 text-white hover:bg-red-500" },
                medium: { wrapper: "bg-yellow-500/10 border-yellow-500/30", icon: "text-yellow-400",     badge: "bg-yellow-400 text-black hover:bg-yellow-400" },
                low:    { wrapper: "bg-muted border-border",              icon: "text-muted-foreground", badge: "bg-secondary text-secondary-foreground hover:bg-secondary" },
              }[flag.severity as "high" | "medium" | "low"] ?? { wrapper: "bg-muted border-border", icon: "text-muted-foreground", badge: "bg-secondary text-secondary-foreground hover:bg-secondary" };
              const basis = basisLabel[flag.basis as string];

              return (
                <div key={idx} className={`p-4 rounded-xl border flex items-start gap-3 ${sev.wrapper}`}>
                  <AlertTriangle className={`w-4 h-4 shrink-0 mt-1 ${sev.icon}`} />
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap mb-1.5">
                      <Badge className={`font-mono text-[10px] uppercase tracking-wider ${sev.badge}`}>{flag.severity} Risk</Badge>
                      {basis && (
                        <span className={`inline-flex items-center text-[10px] font-mono px-1.5 py-0.5 rounded border ${basis.color}`}>
                          {basis.label}
                        </span>
                      )}
                    </div>
                    <p className="text-sm font-medium text-foreground">{flag.description}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Detailed Breakdown Tabs */}
      <div className={`mb-12 transition-all duration-500 delay-200 ${revealed ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"}`}>
        <Tabs defaultValue="seller">
          <TabsList className="grid w-full grid-cols-2 md:grid-cols-4 h-auto p-1 bg-muted/50 rounded-xl mb-4">
            <TabsTrigger value="seller"  className="py-2.5 font-mono text-xs uppercase tracking-wider rounded-lg data-[state=active]:bg-background data-[state=active]:shadow-sm">Seller Rep</TabsTrigger>
            <TabsTrigger value="specs"   className="py-2.5 font-mono text-xs uppercase tracking-wider rounded-lg data-[state=active]:bg-background data-[state=active]:shadow-sm">Specs Reality</TabsTrigger>
            <TabsTrigger value="reviews" className="py-2.5 font-mono text-xs uppercase tracking-wider rounded-lg data-[state=active]:bg-background data-[state=active]:shadow-sm">Review Auth</TabsTrigger>
            <TabsTrigger value="brand"   className="py-2.5 font-mono text-xs uppercase tracking-wider rounded-lg data-[state=active]:bg-background data-[state=active]:shadow-sm">Brand Trust</TabsTrigger>
          </TabsList>
          <div className="p-5 md:p-7 border border-border/50 rounded-2xl bg-card shadow-sm">
            <TabsContent value="seller"  className="mt-0">
              <h3 className="text-base font-bold mb-3 flex items-center gap-2"><ScanLine className="w-4 h-4 text-primary" /> Seller Analysis</h3>
              <p className="text-muted-foreground font-mono text-sm leading-relaxed whitespace-pre-wrap">{result.sellerAnalysis}</p>
            </TabsContent>
            <TabsContent value="specs"   className="mt-0">
              <h3 className="text-base font-bold mb-3 flex items-center gap-2"><FileText className="w-4 h-4 text-primary" /> Specifications Check</h3>
              <p className="text-muted-foreground font-mono text-sm leading-relaxed whitespace-pre-wrap">{result.specsAnalysis}</p>
            </TabsContent>
            <TabsContent value="reviews" className="mt-0">
              <h3 className="text-base font-bold mb-3 flex items-center gap-2"><Search className="w-4 h-4 text-primary" /> Reviews Authenticity</h3>
              <p className="text-muted-foreground font-mono text-sm leading-relaxed whitespace-pre-wrap">{result.reviewsAnalysis}</p>
            </TabsContent>
            <TabsContent value="brand"   className="mt-0">
              <h3 className="text-base font-bold mb-3 flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-primary" /> Brand Verification</h3>
              <p className="text-muted-foreground font-mono text-sm leading-relaxed whitespace-pre-wrap">{result.brandTrustAnalysis}</p>
            </TabsContent>
          </div>
        </Tabs>
      </div>

      {/* Alternatives */}
      {result.alternatives && result.alternatives.length > 0 && (
        <div className={`transition-all duration-500 delay-300 ${revealed ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"}`}>
          <div className="flex items-center justify-between mb-5 pb-4 border-b border-border/50">
            <div>
              <h2 className="text-xl font-bold">Same Product, Better Source</h2>
              <p className="text-muted-foreground font-mono text-xs mt-0.5 uppercase tracking-wider">Tap any card to search that platform</p>
            </div>
            <Badge variant="outline" className="font-mono text-xs text-green-400 border-green-400/30 bg-green-400/5 px-3 py-1">AI Curated</Badge>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {result.alternatives.map((alt: any, idx: number) => {
              const accent = platformAccent[alt.platform?.toLowerCase()] ?? "hover:border-primary/50 hover:shadow-primary/10";
              return (
                <a key={idx} href={alt.url ?? "#"} target="_blank" rel="noopener noreferrer" className="block group">
                  <Card className={`overflow-hidden border-border/50 shadow-sm hover:shadow-lg transition-all duration-200 cursor-pointer h-full ${accent}`}>
                    <CardContent className="p-0 h-full flex flex-col">
                      <div className="p-4 flex gap-3 flex-1">
                        <div className="shrink-0 flex flex-col items-center">
                          <div className="text-[10px] font-mono font-bold text-muted-foreground mb-1.5">Score</div>
                          <TrustScore score={alt.trustScore} size="sm" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center justify-between mb-1.5 gap-2">
                            <Badge variant="secondary" className="px-2 py-0 h-5 text-[10px] font-mono tracking-wider shrink-0">
                              <PlatformIcon platform={alt.platform} className="w-2.5 h-2.5 mr-1" />
                              {alt.platform}
                            </Badge>
                            {alt.price && <span className="font-mono font-bold text-sm text-primary whitespace-nowrap">{alt.price}</span>}
                          </div>
                          <h4 className="font-bold text-sm leading-snug mb-1 line-clamp-2">{alt.title}</h4>
                          <span className="text-xs text-muted-foreground font-mono">{alt.brand}</span>
                        </div>
                      </div>
                      <div className="bg-muted/30 px-4 py-3 border-t border-border/50 flex items-start gap-2">
                        <CheckCircle2 className="w-3.5 h-3.5 text-green-400 shrink-0 mt-0.5" />
                        <p className="text-xs font-mono text-muted-foreground leading-relaxed flex-1">{alt.whyBetter}</p>
                        <ExternalLink className="w-3 h-3 text-muted-foreground/30 group-hover:text-primary shrink-0 transition-colors mt-0.5" />
                      </div>
                    </CardContent>
                  </Card>
                </a>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
