kind = "web"
previewPath = "/"
title = "Lister"
version = "1.0.0"
id = "artifacts/lister"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22560

[services.development]
run = "pnpm --filter @workspace/lister run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/lister", "run", "build" ]
publicDir = "artifacts/lister/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22560"
BASE_PATH = "/"
